apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
        - name: nweather-frontend
          image: us-central1-docker.pkg.dev/weather-app-gke-462718/weather-app/weather-frontend:18
          imagePullPolicy: Always
          ports:
            - containerPort: 80
